version: "3.3"

services:
  nextcloud-db:
    image: mariadb
    container_name: nextcloud-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --innodb_read_only_compressed=OFF
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=nextcloud"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ./nextcloud/mariadb:/var/lib/mysql
    environment:
      - TZ=Europe/Berlin
      - MYSQL_ROOT_PASSWORD=ยง{MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - default

#  myadmin:
#    image: phpmyadmin
#    container_name: nextcloud_myadmin
#    restart: unless-stopped
 #   ports:
 #     - 9021:80
 #   depends_on:
#      mariadb:
#        condition: service_healthy
#    links:
#      - mariadb
#    environment:
#      - TZ=Europe/Berlin
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=nextcloud
#    networks:
#      - internal

  nextcloud-redis:
    image: redis
    container_name: nextcloud-redis
    hostname: nextcloud-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - "./nextcloud/redis:/data"
    networks:
      - default

  nextcloud-app:
    image: nextcloud
    container_name: nextcloud-app
    restart: unless-stopped
    depends_on:
      nextcloud-db:
        condition: service_healthy
      nextcloud-redis:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./nextcloud/nextcloud:/var/www/html 
      - ./nextcloud/apps:/var/www/html/custom_apps 
      - ./nextcloud/config:/var/www/html/config 
      - ./nextcloud/data:/var/www/html/data 
    environment:
      TZ: Europe/Berlin
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES}
      OVERWRITEPROTOCOL: https
      OVERWRITECLIURL: https://${NEXT_CLOUD_DOMAIN}
      OVERWRITEHOST: ${NEXT_CLOUD_DOMAIN}
      REDIS_HOST: nextcloud-redis
      REDIS_HOST_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - web
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`${NEXT_CLOUD_DOMAIN}`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=myresolver"
      - "traefik.http.routers.nextcloud.service=nextcloud"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.http.middlewares.nextcloudsts.headers.stsincludesubdomains=false"
      - "traefik.http.middlewares.nextcloudsts.headers.stspreload=true"
      - "traefik.http.middlewares.nextcloudsts.headers.stsseconds=31536000"
      - "traefik.http.middlewares.nextcloudsts.headers.isdevelopment=false"
      - "traefik.http.routers.service.middlewares=nextcloudsts"
      - "traefik.docker.network=web"

networks:
  web:
    external: true